### ISSUE TITLE
Ubuntu 20 in Docker: Unhandled exception caught by SWT

### ISSUE THREAD

**Issue by Mariyo** [ModelioOpenSource/Modelio#16]
Hello,

I have problem to run Modelio on Ubuntu 20, when I run application I get error: 

```
Unhandled exception caught by SWT: org.eclipse.swt.SWTError: No more handles because no underlying browser available.
   SWT on GTK 2.x detected. It is reccomended to use SWT on GTK 3.x and Webkit2 API.
```

![image](https://user-images.githubusercontent.com/1678254/109852814-7ad86b00-7c55-11eb-8ddc-b1315e7dd5aa.png)

I have found workaround on forum https://www.modelio.org/forum/7-general-help/4528-webkit-internal-error-modelio-4-0.html, but this does not work either:

![image](https://user-images.githubusercontent.com/1678254/109853041-bffc9d00-7c55-11eb-82fb-d8688356e8d1.png)

My version of java:

```
modelio@mariyo-profesia:/$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
```

I tried to use `openjdk-11` but it endup with following application error:

```
!SESSION 2021-03-03 17:57:34.672 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_232
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 -clearPersistedState

!ENTRY org.eclipse.osgi 4 0 2021-03-03 17:57:35.902
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.gtk.OS._cachejvmptr()V
	at org.eclipse.swt.internal.gtk.OS._cachejvmptr(Native Method)
	at org.eclipse.swt.internal.gtk.OS.cachejvmptr(OS.java:499)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:92)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:151)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:147)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

Thank you for any advice!

**Comment by Mariyo** [comment]
PS: here is my repository, where you can reproduce the problem: https://github.com/Mariyo/modelio-in-docker, base image setup you can find here: https://github.com/Mariyo/modelio-in-docker/blob/master/system/Dockerfile

**Comment by yuuyins** [comment]
i'm having the same issue. setting SWT_GTK3 to 0, SWT_WEBKIT2 to 1, SWT_GTK2 to 1 doesn't make a difference.
