### ISSUE TITLE
Doesn't run on the latest JDK

### ISSUE THREAD

**Issue by lfrankel** [ModelioOpenSource/Modelio#3]
Modelio refuses to start for me, and directs me to the log, which contains this:

```
!ENTRY org.eclipse.osgi 4 0 2020-09-09 11:50:41.890
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.modelio.gproject.module.catalog.ModuleXmlExtractor.extractModuleXmlContent(ModuleXmlExtractor.java:167)
	at org.modelio.gproject.module.catalog.ModuleXmlExtractor.getModuleHandle(ModuleXmlExtractor.java:264)
	at org.modelio.gproject.module.catalog.FileModuleStore$FileModuleStoreEntry.getModuleHandle(FileModuleStore.java:522)
	at org.modelio.gproject.module.catalog.FileModuleStore.installModuleArchive(FileModuleStore.java:241)
	at org.modelio.app.ui.lifecycle.OsLifeCycleManager.deliverMdaStoreModules(OsLifeCycleManager.java:302)
	at org.modelio.app.ui.lifecycle.OsLifeCycleManager.initModulesCatalog(OsLifeCycleManager.java:329)
	at org.modelio.app.ui.lifecycle.OsLifeCycleManager.postContextCreate(OsLifeCycleManager.java:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:248)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:139)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.lambda$0(E4Application.java:242)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:238)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException cannot be found by org.modelio.core.project.data_4.0.1.202001081309
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 31 more
```

A brief search suggests that the library in question was removed from the JDK, and that the correct solution is to explicitly package it with the product. See https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j . Workaround is to use an older JDK, or perhaps to find the library myself and put it in my classpath.

**Comment by modelio-cde** [comment]
Hi lfrankel,

Modelio 4.x works with JRE 8 which is embedded in its official release (https://www.modelio.org/downloads/download-modelio.html).

Best regards,
cde
