### ISSUE TITLE
Error creating new project

### ISSUE THREAD

**Issue by owend** [ModelioOpenSource/Modelio#64]
Hello. I just installed the 5.3.1 Debian package on a Ubuntu 20.04 system. I get the following error when creating a new project:

```
17:46:42.297 INFO  org.modelio.platform.project     Running batch: project=null create=false workspace=null
17:46:47.452 INFO  o.modelio.app.project.ui.ext_org Opening project 'Project1' 
17:46:59.031 ERROR org.modelio.platform.project     'ModelerModule' fragment falled DOWN: GPartState RAMC 'ModelerModule': EndMountFail(MOUNTING) => DOWN
17:46:59.033 ERROR org.modelio.platform.project     invalid stored block lengths
java.util.zip.ZipException: invalid stored block lengths
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.readFromInflater(ZipArchiveInputStream.java:586)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.readDeflated(ZipArchiveInputStream.java:551)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.read(ZipArchiveInputStream.java:458)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.skip(ZipArchiveInputStream.java:625)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.closeEntry(ZipArchiveInputStream.java:696)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:234)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:408)
	at org.modelio.vbasic.files.Unzipper.countEntries(Unzipper.java:188)
	at org.modelio.vbasic.files.Unzipper.unzip(Unzipper.java:105)
	at org.modelio.gproject.parts.fragment.GRamcFragment.extractRamcToLocal(GRamcFragment.java:217)
	at org.modelio.gproject.parts.fragment.GRamcFragment.doMountInitRepository(GRamcFragment.java:107)
	at org.modelio.gproject.parts.fragment.AbstractGModelFragment.mount(AbstractGModelFragment.java:207)
	at org.modelio.gproject.project.GProject.addGPart(GProject.java:163)
	at org.modelio.gproject.parts.module.GModule.mount(GModule.java:211)
	at org.modelio.gproject.project.GProject.addGPart(GProject.java:163)
	at org.modelio.gproject.project.GProject.addGPart(GProject.java:123)
	at org.modelio.platform.mda.infra.service.impl.ModuleManagementService.installModule(ModuleManagementService.java:515)
	at org.modelio.platform.project.services.ModulesUpdater.installUpdate(ModulesUpdater.java:195)
	at org.modelio.platform.project.services.ModulesUpdater.installUpdates(ModulesUpdater.java:183)
	at org.modelio.platform.project.services.ModulesUpdater.installMandatoryModules(ModulesUpdater.java:223)
	at org.modelio.platform.project.services.openproject.OpenProjectService.updateModules(OpenProjectService.java:745)
	at org.modelio.platform.project.services.openproject.OpenProjectService.openProject(OpenProjectService.java:271)
	at org.modelio.platform.project.services.ProjectService.openProject(ProjectService.java:261)
	at org.modelio.app.project.ui.openproject.OpenProjectHandler.lambda$0(OpenProjectHandler.java:124)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.util.zip.DataFormatException: invalid stored block lengths
	at java.base/java.util.zip.Inflater.inflateBytesBytes(Native Method)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:385)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.readFromInflater(ZipArchiveInputStream.java:584)
	... 24 common frames omitted
17:46:59.209 WARN  org.modelio.platform.mda.infra   ModelerModule v9.3.00 module start failed : The 'ModelerModule' module has no RAMC model element with {00000000-0000-2710-0000-000000000000} UUID.
17:47:16.366 INFO  org.modelio.app.diagram.api      Modelio/Diagram API 5.3.0.202302231648 - Copyright 2013-2023 Modeliosoft.

``` 

I looked in the /modules/ directory and there is no "ModelerModule" but I assume it's built in. The resulting project "Project1" cannot be closed, and I can't create any diagrams. If I go to the Project configuration, the Module shows as disabled and I can't enable it. 

When I close the app, I get the following error in the logs:
```
 17:54:41.054 INFO  org.modelio.app.project.ui       Closing project 'Project1'
17:54:41.054 ERROR org.modelio.app.ui               Unhandled exception caught by SWT: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
17:54:41.071 ERROR org.modelio.app.ui               Unhandled exception caught by SWT: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
17:54:41.072 INFO  org.modelio.platform.project     GPartState EXMLFRAGMENT 'Project1': Unmount(INSTALLED) => INSTALLED
17:54:41.072 INFO  org.modelio.platform.project     GPartState RAMC 'ModelerModule': Unmount(INSTALLED) => INSTALLED
17:54:41.074 ERROR org.modelio.app.ui               Unhandled exception caught by SWT: java.lang.IllegalStateException: 'ModelerModule' part Unmount transition not allowed from state 'MOUNTING'

```

Any hints welcome. I did re-install once to see if maybe something happened during the install process, but right now the error is repeatable.

**Comment by modelio-cde** [comment]
Hi owend,

I just tried to create a project on Ubuntu 20.04 and didn't reproduce your issue...
You're right, the Modeler Module is built in.
Can you check what you got in the %USERPROFILE%\modelio\workspace\Project1\data\fragments directory ?
That's where the ModelerModule files are supposed to be deployed.

**Comment by owend** [comment]
Interesting. The ModelerModule/content directory is empty. The error implies that when the application tries to create those data/fragments for a new project, that the unzip fails. Can I check where those files are supposed to come from? 

`~/modelio/workspace/Project1/data/fragments
ls -l ModelerModule/
drwxrwxr-x 2 parallels parallels 4096 May 30 17:46 content
ls -l ModelerModule/content/
total 0
`
